#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/ConsenSys/mythril
   """
from sys import exit
import mythril.interfaces.cli
import time


if __name__ == "__main__":
    time_start = time.time()
    mythril.interfaces.cli.main()
    time_end = time.time()
    print('time cost [%ds]'%(time_end-time_start))
    exit()

